---

- name: Get nodes from Inventory and add to Groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - include_role: 
      name: utils_hosts_aws


- name: Generate/Emulate new CVE event (Remediation)
  hosts: aap
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    - name: Set CVE
      set_fact: 
        cve_event_body: |
            {
              "bundle": "rhel",
              "application": "vulnerability",
              "version": "v1.1.0",
              "event_type": "any-cve-known-exploit",
              "timestamp": "2026-07-10T10:19:19.958529",
              "context": {
                "display_name": "randomserver",
                "inventory_id": "704fe5b0-210d-47d5-9483-e8dab3348432",
                "org_id": "15801425"
              },
              "events": [
                {
                  "metadata": {},
                  "payload": {
                    "reported_cve": "CVE-2026-31431",
                    "cvss_score": 7.8,
                    "impact_id": 5,
                    "known_exploit": true,
                    "has_rule": false,
                    "publish_date": "2026-04-22T00:00:00+00:00",
                    "demo_has_remediation": true
                  }
                }
              ],
              "recipients": [
                {
                  "only_admins": false,
                  "ignore_user_preferences": false
                }
              ],
              "org_id": "15801425"
            }
        # {
        #   "bundle": "rhel",
        #   "application": "vulnerability",
        #   "version": "v1.1.0",
        #   "event_type": "any-cve-known-exploit",
        #   "timestamp": "2026-07-10T10:19:19.958529",
        #   "context": {
        #     "display_name": "randomserver",
        #     "inventory_id": "704fe5b0-210d-47d5-9483-e8dab3348432",
        #     "org_id": "15801425"
        #   },
        #   "events": [
        #     {
        #       "metadata": {},
        #       "payload": {
        #         "reported_cve": "CVE-2026-53359",
        #         "cvss_score": 7.8,
        #         "impact_id": 5,
        #         "known_exploit": true,
        #         "has_rule": false,
        #         "publish_date": "2026-07-04T00:00:00+00:00",
        #         "demo_has_remediation": false
        #       }
        #     }
        #   ],
        #   "recipients": [
        #     {
        #       "only_admins": false,
        #       "ignore_user_preferences": false
        #     }
        #   ],
        #   "org_id": "15801425"
        # }

    - name: Create a new CVE Event (Remediation)
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}:10001"
        method: POST
        body: "{{ cve_event_body }}"
        status_code: 200
        body_format: json
        headers:
          Content-Type: "application/json"
          Accept: "application/json; indent=4"
        validate_certs: false
      delegate_to: localhost

    # SAMPLE any-cve-known-exploit

    # {
    #   "bundle": "rhel",
    #   "application": "vulnerability",
    #   "version": "v1.1.0",
    #   "event_type": "any-cve-known-exploit",
    #   "timestamp": "2025-03-19T20:19:19.958529",
    #   "context": {
    #     "display_name": "randomserver",
    #     "inventory_id": "704fe5b0-210d-47d5-9483-e8dab3348432",
    #     "org_id": "13959588"
    #   },
    #   "events": [
    #     {
    #       "metadata": {},
    #       "payload": {
    #         "reported_cve": "CVE-2025-24201",
    #         "cvss_score": 7.5,
    #         "impact_id": 5,
    #         "known_exploit": true,
    #         "has_rule": false,
    #         "publish_date": "2025-03-11T00:00:00+00:00"
    #       }
    #     }
    #   ],
    #   "recipients": [
    #     {
    #       "only_admins": false,
    #       "ignore_user_preferences": false
    #     }
    #   ],
    #   "org_id": "13959588"
    # }

    # SAMPLE system-cve-known-exploit
    # {
    #   "meta":{
    #       "endpoint":"",
    #       "headers":{
    #         "Content-Length":"871",
    #         "Content-Type":"application/json;charset=utf-8",
    #         "Host":"aap.cparada.com:10000",
    #         "User-Agent":"Quarkus REST Client"
    #       },
    #       "received_at":"2026-07-22T14:57:20.511851Z",
    #       "source":{
    #         "name":"redhatinsights.eda.insights",
    #         "type":"redhatinsights.eda.insights"
    #       },
    #       "uuid":"db5cc6f3-6b65-4b6b-b312-bf527f2917f2"
    #   },
    #   "payload":{
    #       "account_id":"None",
    #       "application":"vulnerability",
    #       "bundle":"rhel",
    #       "context":{
    #         "display_name":"ec2-13-221-42-140.compute-1.amazonaws.com",
    #         "inventory_id":"917e67e9-d2bd-4b29-b066-62fccd8d5905",
    #         "org_id":"15801425"
    #       },
    #       "event_type":"system-cve-known-exploit",
    #       "events":[
    #         {
    #             "metadata":{                  
    #             },
    #             "payload":{
    #               "cvss_score":7.8,
    #               "has_rule":false,
    #               "impact_id":5,
    #               "known_exploit":true,
    #               "publish_date":"2025-07-22T00:00:00+00:00",
    #               "reported_cve":"CVE-2025-38352"
    #             }
    #         },
    #         {
    #             "metadata":{            
    #             },
    #             "payload":{
    #               "cvss_score":7.8,
    #               "has_rule":false,
    #               "impact_id":5,
    #               "known_exploit":true,
    #               "publish_date":"2026-04-22T00:00:00+00:00",
    #               "reported_cve":"CVE-2026-31431"
    #             }
    #         }
    #       ],
    #       "org_id":"15801425",
    #       "severity":"CRITICAL",
    #       "source":{
    #         "application":{
    #             "display_name":"Vulnerability"
    #         },
    #         "bundle":{
    #             "display_name":"Red Hat Enterprise Linux"
    #         },
    #         "event_type":{
    #             "display_name":"System vulnerability ""with known exploit"
    #         }
    #       },
    #       "timestamp":"2026-07-22T14:57:19.826173"
    #   }
    # }

    # SAMPLE system-cve-all
    # {
    #   "meta":{
    #       "endpoint":"",
    #       "headers":{
    #         "Content-Length":"193824",
    #         "Content-Type":"application/json;charset=utf-8",
    #         "Host":"aap.cparada.com:10000",
    #         "User-Agent":"Quarkus REST Client"
    #       },
    #       "received_at":"2026-07-22T14:57:21.056212Z",
    #       "source":{
    #         "name":"redhatinsights.eda.insights",
    #         "type":"redhatinsights.eda.insights"
    #       },
    #       "uuid":"6bee8eb9-312d-4c8c-95de-96b8011aba70"
    #   },
    #   "payload":{
    #       "account_id":"None",
    #       "application":"vulnerability",
    #       "bundle":"rhel",
    #       "context":{
    #         "display_name":"ec2-13-221-42-140.compute-1.amazonaws.com",
    #         "inventory_id":"917e67e9-d2bd-4b29-b066-62fccd8d5905",
    #         "org_id":"15801425"
    #       },
    #       "event_type":"system-cve-all",
    #       "events":[
    #         {
    #             "metadata":{            
    #             },
    #             "payload":{
    #               "cvss_score":6.7,
    #               "has_rule":false,
    #               "impact_id":4,
    #               "known_exploit":false,
    #               "publish_date":"2024-08-26T00:00:00+00:00",
    #               "reported_cve":"CVE-2024-44932"
    #             }
    #         },
    #         {
    #             "metadata":{              
    #             },
    #             "payload":{
    #               "cvss_score":5.5,
    #               "has_rule":false,
    #               "impact_id":4,
    #               "known_exploit":false,
    #               "publish_date":"2024-11-05T00:00:00+00:00",
    #               "reported_cve":"CVE-2024-50117"
    #             }
    #         },
    #         {
    #             "metadata":{                  
    #             },
    #             "payload":{
    #               "cvss_score":9.8,
    #               "has_rule":false,
    #               "impact_id":5,
    #               "known_exploit":false,
    #               "publish_date":"2026-01-27T14:00:00+00:00",
    #               "reported_cve":"CVE-2025-15467"
    #             }
    #         }
    #       ],
    #       "org_id":"15801425",
    #       "severity":"IMPORTANT",
    #       "source":{
    #         "application":{
    #             "display_name":"Vulnerability"
    #         },
    #         "bundle":{
    #             "display_name":"Red Hat Enterprise Linux"
    #         },
    #         "event_type":{
    #             "display_name":"System vulnerability"
    #         }
    #       },
    #       "timestamp":"2026-07-22T14:57:19.825739"
    #   }
    # }
