---

- name: Set CVE List Vars
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Set stats for CVE events
      ansible.builtin.set_stats:
        data:
          events: "{{ ansible_eda.event.payload.events }}"

