---

- name: Check CVE Remediations
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    - name: Debug Hostvars
      ansible.builtin.debug:
        var: hostvars['localhost']

    - name: AIOps Lightspeed action payload
      ansible.builtin.set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Debug Payload
      ansible.builtin.debug:
        var: payload

    - name: Get Lightspeed access token using Service Account Client ID and Secret
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: "form-urlencoded"
        body:
          grant_type: client_credentials
          client_id: "{{ lightspeed_client_id }}"
          client_secret: "{{ lightspeed_client_secret }}"
        status_code: 200
      register: sso_response
      
    - name: Query Lightspeed for {{ payload.events[0].payload.reported_cve }}
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/vulnerability/v1/cves/{{ payload.events[0].payload.reported_cve }}"
        method: GET
        headers:
          Authorization: "Bearer {{ sso_response.json.access_token }}"
        status_code: 200
      register: cve_response

    - name: Debug Lightspeed Response
      ansible.builtin.debug:
        var: cve_response    

    - name: Check whether there are Remediations available on Lightspeed for {{ cve_name }}
      ansible.builtin.assert:
        that:
        # real check
          # - (cve_response.json.data.attributes.rules | length > 0) or (cve_response.json.data.attributes.advisories_list | default([]) | length > 0)
        # demo check
          - payload.events[0].payload.demo_has_remediation == true
        fail_msg: "There ARE NO Remediations available on Lightspeed. Going to use AI-based Mitigation"
        success_msg: "There ARE Remediations available on Lightspeed. Security Rules {{ cve_response.json.data.attributes.rules }}, Advisories: {{ cve_response.json.data.attributes.advisories_list }}. Going for Remediations."
        