---

- name: Check CVE Details
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  tasks:
    - name: Debug Hostvars
      ansible.builtin.debug:
        var: hostvars['localhost']

    - name: AIOps Lightspeed action payload
      ansible.builtin.set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Debug Payload
      ansible.builtin.debug:
        var: payload

    - name: Set fact {{ payload.events[0].payload.reported_cve }} Name
      ansible.builtin.set_fact:
        cve_name: "{{ payload.events[0].payload.reported_cve }}"

    - name: Set stats {{ cve_name }} Name
      ansible.builtin.set_stats:
        data:
          cve_name: "{{ cve_name }}"

    - name: Debug {{ cve_name }} Name
      ansible.builtin.debug:
        msg: "CVE Name: {{ cve_name }}"

    - name: Get access token using Service Account Client ID and Secret
      ansible.builtin.uri:
        url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        method: POST
        body_format: "form-urlencoded"
        body:
          grant_type: client_credentials
          client_id: "{{ lightspeed_client_id }}"
          client_secret: "{{ lightspeed_client_secret }}"
        status_code: 200
      register: sso_response

    - name: Query Lightspeed for the affected systems
      ansible.builtin.uri:
        url: "https://console.redhat.com/api/vulnerability/v1/cves/{{ cve_name }}/affected_systems"
        method: GET
        headers:
          Authorization: "Bearer {{ sso_response.json.access_token }}"
        status_code: 200
      register: affected_systems_response
      # ignore_errors: true

    - name: Debug Affected Systems Response
      ansible.builtin.debug:
        var: affected_systems_response

    - name: Set fact Affected Systems ID
      ansible.builtin.set_fact:
        affected_systems_id: "{{ affected_systems_response.json.data | map(attribute='id') | list }}"

    - name: Set stats Affected Systems ID
      ansible.builtin.set_fact:
        affected_systems_id: "{{ affected_systems_id }}"

    - name: Set stats Affected Systems ID
      ansible.builtin.set_stats:
        data:
          affected_systems_id: "{{ affected_systems_id }}"

    - name: Set fact Affected Systems FQDN
      ansible.builtin.set_fact:
        affected_systems_fqdn: "{{ affected_systems_response.json.data | map(attribute='attributes.display_name') | list }}"

    - name: Set stats Affected Systems FQDN
      ansible.builtin.set_stats:
        data:
          affected_systems_fqdn: "{{ affected_systems_fqdn }}"

    - name: Check whether any System is Affected
      ansible.builtin.assert:
        that:
          - affected_systems_id | length > 0
        fail_msg: "There ARE NO Systems affected by {{ cve_name }}. Aborting..."
        success_msg: "There ARE Systems affected by {{ cve_name }}: Continue {{ affected_systems_fqdn }}"
