---

- name: Get AI generated Mitigation Code
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files: vars/main.yml
  vars:
    cve_details: ""
  tasks:
    # - name: Fetch CVE data from Red Hat Security Data API
    #   ansible.builtin.uri:
    #     url: "https://access.redhat.com/hydra/rest/securitydata/cve/{{ cve_name }}.json"
    #     method: GET
    #     return_content: true
    #     status_code: 200
    #   register: cve_response

    # - name: Display CVE details
    #   ansible.builtin.debug:
    #     var: cve_response.json

    # - name: Set the CVE Details
    #   ansible.builtin.set_fact:
    #     cve_details: "{{ cve_response.json.details | default('No details available for this CVE.') }}"

    # - name: Display CVE Mitigation
    #   ansible.builtin.set_fact:
    #     cve_mitigation: "{{ cve_response.json.mitigation.value | default('No mitigation available for this CVE.') }}"

    - name: Fetch Data from VEX/CSAF API for {{ cve_name }}
      uri:
        url: "https://access.redhat.com/security/data/csaf/v2/vex/{{ cve_name.split('-')[1] }}/{{ cve_name | lower }}.json"
        return_content: true
        status_code: 200
      register: cve_response

    - name: Extract and Set CVE Details
      ansible.builtin.set_fact:
        cve_details: "{{ cve_details}}{{ item.category }}: {{ item.text }}\n"
      loop: "{{ cve_response.json.vulnerabilities[0].notes | default([]) }}"

    - name: Debug CVE Details
      debug: 
        msg: "{{ cve_details }}"

    - name: Extract CVE Red Hat Security Bulletin (RHSB) url
      ansible.builtin.set_fact:
        cve_rhsb_url: "{{ item.url }}"
      loop: "{{ cve_response.json.vulnerabilities[0].references | default([]) }}"
      when: "'RHSB' in item.summary" 

    - name: Fetch CVE Red Hat Security Bulletin (RHSB) Content
      ansible.builtin.uri:
        url: "{{ cve_rhsb_url }}"
        return_content: true
        status_code: 200
      when: cve_rhsb_url is defined
      register: cve_rhsb_html

    - name: Extract Executive Summary and Mitigations section from RHSB HTML
      set_fact:
        cve_rhsb_execsummary: "{{ cve_rhsb_html.content |
          regex_search('(?s)<h2>Executive Summary</h2>(.*?)<h2>',
          '\\1', ignorecase=True) | default([], true) }}"
        cve_rhsb_mitigations: "{{ cve_rhsb_html.content |
          regex_search('(?s)<h2>Mitigations</h2>(.*?)<h2>',
          '\\1', ignorecase=True) | default([], true) }}"
      when: cve_rhsb_html.status == 200

    - name: Set Fact Red Hat AI Prompt
      ansible.builtin.set_fact:
        prompt: |
          Write a simple ansible playbook to mitigate {{ cve_name }}.
          The playbbok MUST only cover the RHEL OS for target nodes.
          DON'T include tasks to perform backups, checks or validations.
          DON'T update any software package or kernel binary, DO ONLY mitigation
          based on kernel parameters or similar mitigation measures.
          You SHOULD reboot the systems to apply changes if needed.
          You MUST use the following string as ansible play targets (hosts): 
          '{{ affected_systems_fqdn | join(',') }}'.
          The CVE has the following details:
          {{ cve_details }}
          The Red Hat Security Bulletin containt mitigation details:
          Executive Summary: {{ cve_rhsb_execsummary | default ('', true) }}
          Mitigations: {{ cve_rhsb_mitigations | default ('', true) }}

    - name: Request Mitigation Playbook to Openshift AI
      ansible.builtin.uri:
        url: "{{ ai_endpoint }}"
        method: POST
        body:
          model: "{{ ai_model }}"
          messages: 
            - content: "{{ prompt }}"
        status_code: 200
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ ai_token }}"
        validate_certs: yes
      register: ai_response
      retries: 10
      delay: 5
      until: ai_response.status == 200

    - name: Debug Response from Openshift AI
      debug:
        var: ai_response

    - name: Set Fact Mitigation Ansible Playbook
      ansible.builtin.set_fact:
        generated_playbook: >-
          {{ cve_details | wordwrap(60) |
          comment('plain', prefix='####### DETAILS #######', postfix='#######') }}

          {{ ai_response.json.choices[0].message.reasoning_content |
          wordwrap(60) |
          comment('plain', prefix='####### REASONING #######', postfix='#######') }}
          
          {{ ai_response.json.choices[0].message.content
             .split('```yaml')[1].split('```')[0] | trim }}

    - name: Debug generated Playbook
      ansible.builtin.debug:
        var: generated_playbook

    - name: Set stats generated Playbook
      ansible.builtin.set_stats:
        data:
          generated_playbook: "{{ generated_playbook }}"

