---
- name: AWS AIOps AO Forwarder - New CVE
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: AIOps Lightspeed action payload
      ansible.builtin.set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: Obtain OAuth token
      ansible.builtin.uri:
        url: "{{ ao_webhook_url }}/api/v1/auth/token"
        method: POST
        body_format: form-urlencoded
        body:
          grant_type: client_credentials
          client_id: "{{ ao_webhook_client_id }}"
          client_secret: "{{ ao_webhook_client_secret }}"
        status_code: 200
      register: token_response

    - name: Post event payload to Event-Driven Ansible forwarder endpoint
      ansible.builtin.uri:
        url: "{{ ao_webhook_url }}/api/v1/webhooks/eda/{{ ao_webhook_path_new_system }}"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ token_response.json.access_token }}"
          Content-Type: application/json
        body: 
          "{{ ansible_eda }}"
        status_code: 202
      register: ao_webhook_response

    - name: Debug AO Webhook response
      ansible.builtin.debug:
        msg: "AO Workflow data: {{ ao_webhook_response }}"

    - name: Display execution ID
      ansible.builtin.debug:
        msg: "Workflow execution started: {{ ao_webhook_response.json.execution_id }}"
