---

# - name: Refresh inventory
#   ansible.builtin.meta: refresh_inventory

- name: Get AAP node
  set_fact:
    node_name: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].tags is defined and hostvars[item].tags.Name is match("^aap-1$")

- name: Add AAP node to the aap group
  add_host:
    name: "{{ node_name }}"
    groups: "aap"
  when: node_name is defined

- name: Get RHEL 1 node
  set_fact:
    node_name: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].tags is defined and hostvars[item].tags.Name is match("^rhel-1$")

- name: Add RHEL node to the rhel group
  add_host:
    name: "{{ node_name }}"
    groups: "rhel"
  when: node_name is defined

- name: Get RHEL 2 node
  set_fact:
    node_name: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].tags is defined and hostvars[item].tags.Name is match("^rhel-2$")

- name: Add RHEL node to the rhel group
  add_host:
    name: "{{ node_name }}"
    groups: "rhel"
  when: node_name is defined

- name: Get RHEL 3 node
  set_fact:
    node_name: "{{ item }}"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].tags is defined and hostvars[item].tags.Name is match("^rhel-3$")

- name: Add RHEL3 node to the rhelnew group
  add_host:
    name: "{{ node_name }}"
    groups: "rhelnew"
  when: node_name is defined